### ISSUE TITLE
Version of CUDA (nvcc) must be 11.x

### ISSUE THREAD

**Issue by Housz** [law-dwg/LSQR-CUDA#4]
Thank you for your work.

After tests, some keywords only exist in the version 11.x of CUDA. For example, `CUSPARSE_MV_ALG_DEFAULT` in matrixCUSPARSE.cu.
So I hope the author can modify the Requirements in README for "CUDA (nvcc) v11". Thanks! :)

**Comment by law-dwg** [comment]
Hey @Housz , thanks for bringing this to my attention! I will look into it and open a pull request

**Comment by law-dwg** [comment]
Hey @Housz , instead, I updated the code to support both nvcc v11 and v12, such that the README should now be correct, let me know if you still have issues!
